### ISSUE TITLE
make 'cuv lessopen' the default command

### ISSUE THREAD

**Issue by meejah** [meejah/cuvner#5]
If you type `cuv <filename>` then you should get the result of `cuv lessopen` passed through `$PAGER` -- that is, syntax-highlighted, coverage-coloured view of the file.

(Thanks @kneufeld)

**Comment by kneufeld** [comment]
may be helpful https://gist.github.com/orbitbot/ffd5eb9df5fde0655e67

**Comment by meejah** [comment]
Implemented: https://github.com/meejah/cuvner/commit/a396c8b66f603851ac702dd7e8160175b7e7edcf

**Comment by meejah** [comment]
(this is in 16.3.0)
